sonar.projectKey=mces58_Hangmanify
sonar.organization=hangmanify
sonar.projectName=Hangmanify
sonar.projectVersion=1.0
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.language=ts
sonar.exclusions=**/android/**,**/ios/**,**/tests/**/*.*,**/node_modules/**
